# Generated by Django 6.0.2 on 2026-02-11 02:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OverdueSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fee_per_day", models.DecimalField(decimal_places=2, max_digits=10)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="borrowedbook",
            name="damage_fee",
        ),
        migrations.RemoveField(
            model_name="borrowedbook",
            name="is_overdue",
        ),
        migrations.RemoveField(
            model_name="borrowedbook",
            name="overdue_days",
        ),
        migrations.RemoveField(
            model_name="borrowedbook",
            name="overdue_fee",
        ),
        migrations.AddField(
            model_name="digitalresource",
            name="keywords",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="physicalbook",
            name="details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="physicalbook",
            name="keywords",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="borrowedbook",
            name="borrowed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="borrowedbook",
            name="status",
            field=models.CharField(
                choices=[
                    ("borrowed", "Borrowed"),
                    ("returned", "Returned"),
                    ("overdue", "Overdue"),
                ],
                default="borrowed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="researchrepository",
            name="keywords",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="digitalresource",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.category",
            ),
        ),
        migrations.AddField(
            model_name="researchrepository",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.category",
            ),
        ),
        migrations.AlterField(
            model_name="physicalbook",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.category",
            ),
        ),
        migrations.AddField(
            model_name="borrowedbook",
            name="overdue_setting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.overduesetting",
            ),
        ),
    ]
