# Generated by Django 6.0.2 on 2026-03-17 00:48

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_booksuggestion_userprofile_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booksuggestion",
            name="isbn",
        ),
        migrations.RemoveField(
            model_name="borrowedbook",
            name="book",
        ),
        migrations.RemoveField(
            model_name="digitalresource",
            name="file_url",
        ),
        migrations.RemoveField(
            model_name="researchrepository",
            name="abstract",
        ),
        migrations.RemoveField(
            model_name="researchrepository",
            name="file_url",
        ),
        migrations.AddField(
            model_name="digitalresource",
            name="details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="digitalresource",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, null=True
            ),
        ),
        migrations.AddField(
            model_name="digitalresource",
            name="file_path",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="digitalresource",
            name="image_path",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="physicalbook",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, null=True
            ),
        ),
        migrations.AddField(
            model_name="researchrepository",
            name="best_thesis",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="researchrepository",
            name="details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="researchrepository",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, null=True
            ),
        ),
        migrations.AddField(
            model_name="researchrepository",
            name="file_path",
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name="BookCopy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("copy_number", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("borrowed", "Borrowed"),
                            ("damaged", "Damaged"),
                            ("lost", "Lost"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("barcode", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copies",
                        to="api.physicalbook",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="borrowedbook",
            name="copy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.bookcopy",
            ),
        ),
    ]
