# Generated by Django 6.0.2 on 2026-03-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_userprofile_is_email_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowedbook",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("borrowed", "Borrowed"),
                    ("returned", "Returned"),
                    ("overdue", "Overdue"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
