# Generated by Django 6.0.2 on 2026-03-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_borrowedbook_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="physicalbook",
            name="image_path",
            field=models.TextField(null=True),
        ),
    ]
