# Generated by Django 6.0.2 on 2026-04-07 11:36

from django.db import migrations
from pgvector.django import VectorField


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_physicalbook_image_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="digitalresource",
            name="embedding",
        ),
        migrations.RemoveField(
            model_name="physicalbook",
            name="embedding",
        ),
        migrations.RemoveField(
            model_name="researchrepository",
            name="embedding",
        ),
        migrations.AddField(
            model_name="digitalresource",
            name="embedding",
            field=VectorField(blank=True, null=True, dimensions=3072),
        ),
        migrations.AddField(
            model_name="physicalbook",
            name="embedding",
            field=VectorField(blank=True, null=True, dimensions=3072),
        ),
        migrations.AddField(
            model_name="researchrepository",
            name="embedding",
            field=VectorField(blank=True, null=True, dimensions=3072),
        ),
    ]